REVOKE ALL ON FUNCTION public.sync_subscription_tier() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.sync_subscription_to_fan_pass() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.update_level_on_xp() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.award_points(uuid, integer, integer, tx_type, text, text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.award_points_v2(uuid, integer, integer, text, text, text, boolean) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.complete_mission(uuid, text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.spend_cabo_coins(uuid, integer, text, text, text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.recalculate_standings(text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.admin_list_fan_passes() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.admin_recalculate_standings(text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.run_level_at_risk_warning() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.run_level_demotion_check() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.run_subscription_expiry_check() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.is_admin(uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.is_super_admin(uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.is_minor_user(uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.has_role(uuid, app_role) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.business_location_id(uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.check_level_maintenance(uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.record_game_play(text, integer, jsonb) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.redeem_reward(uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.check_username_available(text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.get_leaderboard(integer) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.generate_pass_code() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.generate_pass_code(pass_tier, text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.handle_new_user() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.grant_admin_for_founder_email() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.match_events_sync_score() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.matches_refresh_standings() FROM PUBLIC;

-- Re-grant only what the app needs
GRANT EXECUTE ON FUNCTION public.check_username_available(text) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.get_leaderboard(integer) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.has_role(uuid, app_role) TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_admin(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_super_admin(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_minor_user(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.business_location_id(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.check_level_maintenance(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_list_fan_passes() TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_recalculate_standings(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.run_level_at_risk_warning() TO authenticated;
GRANT EXECUTE ON FUNCTION public.run_level_demotion_check() TO authenticated;
GRANT EXECUTE ON FUNCTION public.run_subscription_expiry_check() TO authenticated;
GRANT EXECUTE ON FUNCTION public.record_game_play(text, integer, jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.redeem_reward(uuid) TO authenticated;