GRANT EXECUTE ON FUNCTION public.award_points(uuid, integer, integer, tx_type, text, text) TO service_role;
GRANT EXECUTE ON FUNCTION public.award_points_v2(uuid, integer, integer, text, text, text, boolean) TO service_role;
GRANT EXECUTE ON FUNCTION public.complete_mission(uuid, text) TO service_role;
GRANT EXECUTE ON FUNCTION public.spend_cabo_coins(uuid, integer, text, text, text) TO service_role;
GRANT EXECUTE ON FUNCTION public.recalculate_standings(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.has_role(uuid, app_role) TO service_role;
GRANT EXECUTE ON FUNCTION public.is_admin(uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.is_super_admin(uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.is_minor_user(uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.business_location_id(uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.check_level_maintenance(uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.check_username_available(text) TO service_role;
GRANT EXECUTE ON FUNCTION public.get_leaderboard(integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.generate_pass_code() TO service_role;
GRANT EXECUTE ON FUNCTION public.generate_pass_code(pass_tier, text) TO service_role;
GRANT EXECUTE ON FUNCTION public.record_game_play(text, integer, jsonb) TO service_role;
GRANT EXECUTE ON FUNCTION public.redeem_reward(uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.admin_list_fan_passes() TO service_role;
GRANT EXECUTE ON FUNCTION public.admin_recalculate_standings(text) TO service_role;